### PR TITLE
Upgrading Gradle wrapper from 4.9 to 5.0

### PR DESCRIPTION
**Pull request by Thunderforge**
Upgrading to the latest version of the Gradle wrapper.

Note that before this change, `gradle/wrapper/gradle-wrapper.jar` was previously generated by Gradle 4.2 (see `META-INF` within the jar). This one is generated by Gradle 5.0.

### CODE REVIEW

**Comment by Thunderforge** [comment]
It looks like AppVeyor failed because NUnit wasn't installed? Is that an error on my end or AppVeyor's end?

**Comment by gluck** [comment]
The error seems to be:
```Downloading & Unpacking NUnit 3.0.1 from https://github.com/nunit/nunit/releases/download/3.0.1/NUnit-3.0.1.zip
Invalid cookie header: "Set-Cookie: has_recent_activity=1; path=/; expires=Mon, 26 Nov 2018 19:16:08 -0000". Invalid 'expires' attribute: Mon, 26 Nov 2018 19:16:08 -0000
Invalid cookie header: "Set-Cookie: logged_in=no; domain=.github.com; path=/; expires=Fri, 26 Nov 2038 18:16:08 -0000; secure; HttpOnly". Invalid 'expires' attribute: Fri, 26 Nov 2038 18:16:08 -0000```

The closest I can find is https://github.com/gradle/gradle/issues/1596
It's fixed on gradle side (supposedly), but maybe we need to upgrade httpclient somewhere else ?

**Comment by gluck** [comment]
Actually I don't think we can upgrade gradle because of :
https://github.com/bintray/gradle-bintray-plugin/issues/253

And we can't upgrade bintray plugin to 1.8.1 because it's not compatible w/ plugindev (which is deprecated but we haven't moved yet out of it ....)

Sorry ... :'(

**Comment by Thunderforge** [comment]
@gluck Too bad that we can't upgrade Gradle because of the Bintray plugin. I'll close this.

**Comment by timotei** [comment]
@gluck Can't we use another plugin like https://github.com/bintray/gradle-bintray-plugin ?

**Comment by ngyukman** [comment]
it is already gradle-bintray-plugin but the one not working is plugindev, which needs some refactoring to replace

**Comment by ngyukman** [comment]
https://github.com/etiennestuder/gradle-plugindev-plugin/issues/34

the issue has been solved

**Pull request closed without merging**
