### PR TITLE
using : (instead =) for passing arguments to msbuild

### PR DESCRIPTION
**Pull request by marcozwyssig**

### CODE REVIEW

**Comment by gluck** [comment]
Not sure that's what @jonathanmorley had in mind when he pushed #25 .
I don't use these extra properties myself, so I'll rely on your (agreed) point of view :smile:

**Comment by gluck** [comment]
Actually as far as both [msbuild](https://msdn.microsoft.com/en-us/library/ms164311.aspx) and [xbuild](http://manpages.ubuntu.com/manpages/lucid/man1/xbuild.1.html), /X=Y doesn't seem useful outside of properties, which is already covered in the plugin (parameters).

**Comment by jonathanmorley** [comment]
As I mentioned in the readme, I have been using this for constructs such as `ext["flp1:LogFile"] = file("${project.name}.errors.log").getPath() + ";ErrorsOnly;Verbosity=diag"`.
Which now that I look at the msbuild docs again, seems semantically wrong.

They should be `ext["flp1"] = "LogFile=" + file("${project.name}.errors.log").getPath() + ";ErrorsOnly;Verbosity=diag"`

I'm ok with this, lets just change the readme to reflect these changes though

**Comment by gluck** [comment]
Thx you both ! I'll merge it and fix the doc

**Pull request merged**
